Repository VishnuAmit/LapProFix, pull requests merged in 2024-10, with the labels that each got.

#2 Done with the signup
  .env
  app/api/login/route.ts
  app/api/signup/route.ts
  app/dashboard/page.tsx
  app/layout.tsx
  app/page.tsx
  app/signup/page.tsx
  components/Dashboard/NewsLatterBox.tsx
  components/Dashboard/index.tsx
  db/config.ts
  models/userModels.ts
  package-lock.json
  package.json
  tsconfig.json
Labels: good first issue, Hacktoberfest

#4 signup/login done
  app/api/auth/[...nextauth]/route.js
  app/api/login/route.ts
  app/signin/page.js
  app/signup/page.tsx
  auth.js
  package-lock.json
  package.json
Labels: enhancement, Hacktoberfest, hacktoberfest-accepted

#6 Dashboard Implemented
  app/dashboard/page.tsx
  app/signin/page.js
  app/signup/page.tsx
  package-lock.json
  package.json
  pnpm-lock.yaml
Labels: enhancement, Hacktoberfest

#10 Done with required changes
  README.md
  app/page.tsx
  components/Pricing/PricingBox.tsx
  components/Pricing/index.tsx
  package-lock.json
  package.json
Labels: documentation, Hacktoberfest, hacktoberfest-accepted

#17 Faqs update
  app/api/Faq/add/route.ts
  app/api/Faq/getall/route.ts
  app/dashboard/page.tsx
  components/Dashboard/NewsLatterBox.tsx
  components/Faq/Accordion.tsx
  components/Faq/Faqs.tsx
  components/Header/index.tsx
  db/config.ts
  models/FaqModels.ts
Labels: enhancement, hacktoberfest-accepted

#14 faqs Page added
  app/faq/page.tsx
  components/Faq/Accordion.tsx
  components/Faq/Modal.tsx
  components/Header/menuData.tsx
Labels: enhancement, Hacktoberfest, hacktoberfest-accepted

#24 feature - LapProFix MongoDB Atlas Integration #7
  .env
  db/config.ts
Labels: enhancement, Hacktoberfest, hacktoberfest-accepted

#25 Issue#19: Improvised navbar text color issues
  components/Header/index.tsx
Labels: bug, Hacktoberfest, hacktoberfest-accepted, level-1

#27 email login/signup fix
  app/api/auth/[...nextauth]/route.js
  app/dashboard/page.tsx
  app/signin/page.tsx
  app/signup/page.tsx
  tsconfig.json
Labels: bug, Hacktoberfest, hacktoberfest-accepted

#32 [Refactor] 🔧 Add Best Practices for Configuration, Dependency Management, and Commit Messages
  .commitlintrc
  .env.example
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  app/dashboard/page.tsx
  app/signin/page.tsx
  app/signup/page.tsx
  db/config.ts
  next-env.d.ts
  package-lock.json
  package.json
  pnpm-lock.yaml
Labels: bug, good first issue, Hacktoberfest, hacktoberfest-accepted

#35 Fixed #22: images of authors now loading
  components/Blog/blogData.tsx
Labels: bug, Hacktoberfest, hacktoberfest-accepted

#49 Docs : Added contributor section to README.md
  README.md
Labels: documentation, Hacktoberfest, hacktoberfest-accepted, gssoc-24

#48 [Feature] 🐳 Dockerize Next.js application with MongoDB for consistent development environments
  .dockerignore
  .env.example
  Dockerfile
  compose.yml
Labels: enhancement, Hacktoberfest, hacktoberfest-accepted, level-3, gssoc-ext

#52 Enhancing servicespages #29
  app/dashboard/page.tsx
  app/layout.tsx
  app/services/apple/page.tsx
  app/services/instantbook/page.tsx
  app/services/layout.tsx
  app/services/others/page.tsx
  app/services/themeProvider.tsx
  app/services/windows/page.tsx
  components/Cart/index.tsx
  components/Navbar/index.tsx
  components/Search/index.tsx
  components/Toast/index.tsx
  package.json
  pnpm-lock.yaml
Labels: enhancement, Hacktoberfest, hacktoberfest-accepted, level-2, gssoc-ext
